"""Command-line entry point for Spider Guardian."""

from __future__ import annotations

import argparse
import logging
import os
import sys
from typing import Optional, Sequence

try:  # Allow execution both as package module and standalone script
    from .config import ChatProviderConfig, SpiderGuardianConfig
except ImportError:  # pragma: no cover - fallback for direct execution
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))
    from spider_guardian.config import ChatProviderConfig, SpiderGuardianConfig
CHAT_MODEL_CHOICES = (
    # Small models (fast, low memory)
    "distilgpt2",
    "gpt2",
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    "sentence-transformers/all-MiniLM-L6-v2",
    "sentence-transformers/all-mpnet-base-v2",
    "distilbert-base-uncased",
    "allenai/longformer-base-4096",
    "microsoft/phi-2",
    # Medium models (6-7B params)
    "mistralai/Mistral-7B-Instruct-v0.2",
    "openchat/openchat-3.5-0106",
    "Qwen/Qwen1.5-7B-Chat",
    "NousResearch/Nous-Hermes-2-Mistral-7B-DPO",
    "TheBloke/Mistral-7B-Instruct-v0.2-GPTQ",
    "TheBloke/CodeLlama-7B-Instruct-GPTQ",
    "TheBloke/Mistral-7B-v0.1-GPTQ",
    "TheBloke/zephyr-7B-beta-GPTQ",
    "HuggingFaceH4/zephyr-7b-beta",
    "google/gemma-7b-it",
    "Trelis/Trelis-7B-v0.1",
    "Open-Orca/Mistral-7B-OpenOrca",
    # Large models (13B+ params)
    "meta-llama/Llama-2-13b-chat-hf",
    "Qwen/Qwen1.5-14B-Chat",
    "TheBloke/Llama-2-13B-chat-GPTQ",
    "TheBloke/CodeLlama-13B-Instruct-GPTQ",
    "meta-llama/Llama-2-70b-chat-hf",
    "TheBloke/Llama-2-70B-chat-GPTQ",
    "TheBloke/CodeLlama-34B-Instruct-GPTQ",
    "TheBloke/Nous-Hermes-2-Yi-34B-GPTQ",
    "TheBloke/Yi-34B-Chat-GPTQ",
    # Other models
    "meta-llama/Llama-2-7b-chat-hf",
    "TheBloke/Nous-Hermes-2-Mistral-7B-DPO-GPTQ",
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Spider Guardian bot")
    parser.add_argument(
        "--stream-posts",
        type=int,
        default=0,
        help="Stream and display recent spider posts every 60s (set >0 to enable)",
    )
    parser.add_argument(
        "--dataset",
        dest="dataset_path",
        default=None,
        help="Path to HuggingFace dataset generated by prepare_dataset.py",
    )
    parser.add_argument(
        "--build-index",
        action="store_true",
        help="Build vector index and exit",
    )
    parser.add_argument(
        "--respond",
        type=int,
        default=0,
        help="Fetch posts and reply up to N times (0 disables)",
    )
    parser.add_argument(
        "--collect-feedback",
        action="store_true",
        help="Fetch replies to bot comments and update feedback model",
    )
    parser.add_argument(
        "--collect-trending",
        action="store_true",
        help="Collect trending posts into a short-retention store for tone/style",
    )
    parser.add_argument(
        "--trending-mode",
        choices=("live", "top", "latest"),
        default="top",
        help="Search mode for trending collection (default: top)",
    )
    parser.add_argument(
        "--trending-hours",
        type=int,
        default=24,
        help="Approximate window for trending sampling (used only for filtering in store retrieval)",
    )
    parser.add_argument(
        "--trending-retention-days",
        type=int,
        default=3,
        help="Retention for trending store before purge",
    )
    parser.add_argument(
        "--context-top-k",
        type=int,
        default=None,
        help="Number of context chunks to retrieve per tweet (set 0 to disable context retrieval)",
    )
    parser.add_argument(
        "--context-max-chars",
        type=int,
        default=None,
        help="Maximum characters per context chunk included in the prompt",
    )
    parser.add_argument(
        "--context-chunk-overlap",
        type=int,
        default=None,
        help="Approximate number of trailing characters to overlap between adjacent context chunks",
    )
    parser.add_argument(
        "--context-max-snippets",
        type=int,
        default=None,
        help="Maximum number of context snippets to include in each prompt",
    )
    parser.add_argument(
        "--human-posts-top-k",
        type=int,
        default=None,
        help="Number of saved human tweets to include alongside article context (set 0 to disable)",
    )
    parser.add_argument(
        "--human-posts-path",
        type=str,
        default=None,
        help="Path to JSONL file of saved human posts used for stylistic retrieval",
    )
    parser.add_argument(
        "--human-style-examples",
        type=int,
        default=None,
        help="Maximum number of human tone samples to feed into the prompt",
    )
    parser.add_argument(
        "--reply-min-words",
        type=int,
        default=None,
        help="Minimum word count for generated replies",
    )
    parser.add_argument(
        "--reply-max-words",
        type=int,
        default=None,
        help="Maximum word count for generated replies",
    )
    parser.add_argument(
        "--twitter-transport",
        choices=("selenium",),
        default=None,
        help="Transport (selenium)",
    )
    parser.add_argument(
        "--selenium-driver",
        choices=("chrome", "firefox"),
        default="firefox",
        help="Browser engine for Selenium (chrome or firefox)",
    )
    parser.add_argument(
        "--selenium-headless",
        dest="selenium_headless",
        action="store_true",
        help="Run Selenium headless",
    )
    parser.add_argument(
        "--selenium-visible",
        dest="selenium_headless",
        action="store_false",
        help="Run Selenium with visible window",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        help="Logging level (default: INFO)",
    )
    parser.add_argument(
        "--langsmith",
        action="store_true",
        help="Enable LangSmith tracing if LANGCHAIN_* env vars are set (prints instructions if missing)",
    )
    parser.add_argument(
        "--langsmith-project",
        type=str,
        default=None,
        help="Override LANGCHAIN_PROJECT for this run",
    )
    parser.add_argument(
        "--neptune",
        action="store_true",
        help="Enable Neptune run if NEPTUNE_* env vars are set (prints instructions if missing)",
    )
    parser.add_argument(
        "--neptune-project",
        type=str,
        default=None,
        help="Override NEPTUNE_PROJECT for this run",
    )
    parser.add_argument(
        "--neptune-tags",
        type=str,
        default=None,
        help="Comma-separated list of Neptune tags",
    )
    parser.add_argument(
        "--init-sql",
        action="store_true",
        help="Initialise the SQL database file (creates data/spider_guardian.sqlite)",
    )
    parser.add_argument(
        "--migrate-to-sql",
        type=str,
        default=None,
        help="Path to a CSV/TSV file to import into the SQL database",
    )
    parser.add_argument(
        "--csv-delimiter",
        type=str,
        default=",",
        help="Delimiter for --migrate-to-sql (default: ,)",
    )
    parser.add_argument(
        "--test-one-word-reply",
        action="store_true",
        default=False,
        help="Reply with single word ('Guardian') for reply editor debugging",
    )
    parser.add_argument(
        "--reply-to-replies",
        action="store_true",
        default=False,
        help="If set, also reply to tweets that are replies (default: False)",
    )
    parser.add_argument(
        "--chat-model",
        type=str,
        choices=CHAT_MODEL_CHOICES,
        default="Open-Orca/Mistral-7B-OpenOrca",
        help="Model name for chat replies.",
    )
    parser.add_argument(
        "--provider",
        type=str,
        choices=("local", "langchain"),
        default="local",
        help="Generation provider backend (local transformers or langchain)",
    )
    parser.add_argument(
        "--device",
        type=str,
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Device to use for model inference: auto (prefer CUDA if available), cpu, or cuda (error if unavailable)"
    )
    parser.add_argument(
        "--periodic-updates",
        action="store_true",
        help="Enable periodic updates for datasets and databases."
    )
    parser.add_argument(
        "--post",
        type=str,
        default=None,
        help="Post a standalone tweet with the given text and exit",
    )
    parser.add_argument(
        "--auto-post",
        action="store_true",
        help="Generate and post an educational spider-related tweet automatically and exit",
    )
    parser.add_argument(
        "--update-interval",
        type=int,
        default=3600,
        help="Interval in seconds for periodic updates (default: 3600 seconds)."
    )
    parser.add_argument(
        "--min-followers",
        type=int,
        default=0,
        help="Only reply to authors with at least this many followers (0 = no filter)"
    )
    parser.add_argument(
        "--max-followers",
        type=int,
        default=0,
        help="Only reply to authors with at most this many followers (0 = no limit)"
    )
    parser.add_argument(
        "--min-impressions",
        type=int,
        default=0,
        help="Only reply to tweets with at least this many impressions/views"
    )
    parser.add_argument(
        "--max-empty-searches",
        type=int,
        default=5,
        help="Maximum consecutive searches with no qualifying tweets before giving up (default: 5)"
    )
    parser.add_argument(
        "--first-tweet-only",
        action="store_true",
        help="Reply to the first tweet found and skip follower/impression filtering and scoring"
    )
    parser.add_argument(
        "--author-wait-seconds",
        type=int,
        default=600,
        help="Seconds to wait between author profile requests (default: 600, i.e. 10 minutes)"
    )
    return parser


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    return build_parser().parse_args(argv)


def configure_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[logging.StreamHandler()],
    )


def build_config(args: argparse.Namespace) -> SpiderGuardianConfig:
    cfg = SpiderGuardianConfig()
    if args.dataset_path:
        cfg.dataset_path = args.dataset_path
    if args.twitter_transport:
        cfg.twitter_transport = args.twitter_transport
    if args.selenium_driver:
        cfg.selenium_driver = args.selenium_driver
    if getattr(args, "selenium_headless", None) is not None:
        cfg.selenium_headless = args.selenium_headless
    if args.context_top_k is not None:
        cfg.vector_top_k = max(0, args.context_top_k)
    if args.context_max_chars is not None:
        cfg.context_max_chars = max(50, args.context_max_chars)
    if getattr(args, "context_chunk_overlap", None) is not None:
        cfg.context_chunk_overlap = max(0, args.context_chunk_overlap)
    if getattr(args, "context_max_snippets", None) is not None:
        cfg.context_max_snippets = max(1, args.context_max_snippets)
    if getattr(args, "human_posts_top_k", None) is not None:
        cfg.human_posts_top_k = max(0, args.human_posts_top_k)
    if getattr(args, "human_posts_path", None):
        cfg.human_posts_path = args.human_posts_path
    if getattr(args, "human_style_examples", None) is not None:
        cfg.human_style_examples = max(0, args.human_style_examples)
    if getattr(args, "reply_min_words", None) is not None:
        cfg.reply_min_words = max(3, args.reply_min_words)
    if getattr(args, "reply_max_words", None) is not None:
        cfg.reply_max_words = max(cfg.reply_min_words + 1, args.reply_max_words)
    if args.chat_model:
        backend = getattr(args, "provider", "local")
        cfg.providers = (ChatProviderConfig(name=backend, model=args.chat_model),)
    # Add device to config
    if hasattr(args, "device"):
        cfg.device = args.device
    if getattr(args, "trending_retention_days", None) is not None:
        # attach dynamically for use by bot without changing dataclass fields
        setattr(cfg, "trending_retention_days", max(1, args.trending_retention_days))
    # Attach follower/impression filters
    if getattr(args, "min_followers", None) is not None:
        setattr(cfg, "min_followers", max(0, args.min_followers))
    if getattr(args, "max_followers", None) is not None:
        setattr(cfg, "max_followers", max(0, args.max_followers))
    if getattr(args, "min_impressions", None) is not None:
        setattr(cfg, "min_impressions", max(0, args.min_impressions))
    if getattr(args, "max_empty_searches", None) is not None:
        setattr(cfg, "max_empty_searches", max(1, args.max_empty_searches))
    if getattr(args, "author_wait_seconds", None) is not None:
        setattr(cfg, "author_wait_seconds", max(0, args.author_wait_seconds))
    return cfg


def run_bot(args: argparse.Namespace, config: SpiderGuardianConfig) -> int:
    try:  # Allow execution both as package module and standalone script
        from .bot import SpiderGuardianBot
    except ImportError:  # pragma: no cover - fallback for direct execution
        from spider_guardian.bot import SpiderGuardianBot

    logging.info("Chat reply model: %s", config.providers[0].model)
    try:
        from .telemetry import telemetry
    except Exception:
        telemetry = None  # type: ignore
    bot = SpiderGuardianBot(config)
    bot.build_vector_index()

    # Telemetry initialisation (best effort)
    if telemetry is not None:
        telemetry.enable_langsmith(bool(getattr(args, "langsmith", False)), project=getattr(args, "langsmith_project", None))
        tags = [t.strip() for t in (getattr(args, "neptune_tags", None) or "").split(",") if t.strip()] or None
        telemetry.enable_neptune(bool(getattr(args, "neptune", False)), project=getattr(args, "neptune_project", None), tags=tags)

    # SQL store setup/migration (optional)
    if getattr(args, "init_sql", False) or getattr(args, "migrate_to_sql", None):
        try:
            from .storage.sql import SQLDataStore
            store = SQLDataStore(config.sql_database_path)
            logging.info("SQL database initialised at %s", store.path)
            if getattr(args, "migrate_to_sql", None):
                from .storage.migrator import migrate_csv_to_sql
                csv_path = args.migrate_to_sql
                count = migrate_csv_to_sql(csv_path, store=store, delimiter=args.csv_delimiter)
                logging.info("Imported %d row(s) from %s into %s", count, csv_path, store.path)
        except Exception as exc:
            logging.error("SQL setup/migration failed: %s", exc)

    # Handle standalone post and exit
    if getattr(args, "post", None):
        post_text = args.post.strip()
        if not post_text:
            logging.error("Cannot post empty text")
            return 1
        
        logging.info("🚀 Posting standalone tweet: %r", post_text[:60])
        bot.ensure_twitter_client()
        
        try:
            tweet_id = bot.twitter_client.post_tweet(post_text)
            if tweet_id:
                url = f"https://x.com/{bot.twitter_client.username}/status/{tweet_id}"
                logging.info("✅ Tweet posted successfully: %s", url)
                
                # Log to LangSmith dataset
                bot.log_my_tweet(
                    text=post_text,
                    tweet_id=tweet_id,
                    url=url,
                    source="cli_post"
                )
                return 0
            else:
                logging.error("❌ Failed to post tweet")
                return 1
        except Exception as exc:
            logging.error("❌ Error posting tweet: %s", exc)
            return 1

    # Handle auto-generated post and exit
    if getattr(args, "auto_post", False):
        logging.info("🤖 Generating educational spider post...")
        post_text = bot.generate_auto_post()
        
        logging.info("🚀 Posting auto-generated tweet: %r", post_text[:60])
        bot.ensure_twitter_client()
        
        try:
            tweet_id = bot.twitter_client.post_tweet(post_text)
            if tweet_id:
                url = f"https://x.com/{bot.twitter_client.username}/status/{tweet_id}"
                logging.info("✅ Auto-generated tweet posted successfully: %s", url)
                
                # Log to LangSmith dataset
                bot.log_my_tweet(
                    text=post_text,
                    tweet_id=tweet_id,
                    url=url,
                    source="auto_post"
                )
                return 0
            else:
                logging.error("❌ Failed to post auto-generated tweet")
                return 1
        except Exception as exc:
            logging.error("❌ Error posting auto-generated tweet: %s", exc)
            return 1

    if args.build_index and not args.respond and not args.collect_feedback and not args.stream_posts:
        logging.info("Vector index built successfully. Exiting.")
        return 0

    while True:
        if args.stream_posts:
            bot.stream_spider_posts(interval=60)

        if args.respond:
            bot.respond_to_tweets(
                limit=args.respond,
                test_one_word_reply=args.test_one_word_reply,
                reply_to_replies=args.reply_to_replies,
                first_tweet_only=getattr(args, "first_tweet_only", False),
            )
            
            # If first_tweet_only mode, exit immediately after responding
            if getattr(args, "first_tweet_only", False):
                logging.info("✅ first_tweet_only mode: Reply sent, exiting cleanly.")
                # return 0

        if args.collect_feedback:
            bot.collect_and_learn()

        if getattr(args, "collect_trending", False):
            count = bot.collect_trending(
                hours=max(1, args.trending_hours),
                retention_days=max(1, args.trending_retention_days),
                mode=args.trending_mode,
            )
            logging.info("Collected %d trending posts into store", count)

        try:
            from .langsmith.visualize_models import (
                fetch_data_from_spider_guardian,
                fetch_replies_with_metrics,
                generate_langsmith_visualization,
                plot_engagement_metrics,
            )

            # Fetch data from Spider Guardian database
            spider_guardian_data = fetch_data_from_spider_guardian()

            # Visualize engagement metrics
            plot_engagement_metrics(spider_guardian_data, save_path='resultats', title='spider_guardian_metrics')

            print(f'REMEMBER YOU HAVE TO CHECK THE RESULTATS FOLDER FOR THE GENERATED METRICS PLOT! resultats/engagement_metrics_spider_guardian_metrics.png')

            # Fetch replies with metrics
            replies_with_metrics = fetch_replies_with_metrics()
            logging.info("Fetched replies with metrics: %s", replies_with_metrics)

            # Generate LangSmith visualization
            generate_langsmith_visualization(spider_guardian_data)
        except Exception as exc:
            logging.warning("Skipping engagement visualizations: %s", exc)

        # Fetch conversations from the database
        logging.info("Fetching conversations from the database...")
        conversations = bot.fetch_conversations()
        logging.info(f"Fetched {len(conversations)} conversations needing replies.")

        # Process each conversation (only those where someone else replied last)
        for conversation in conversations:
            logging.info(
                f"Processing conversation {conversation['conversation_id']}: "
                f"{conversation['original_tweet'][:50]}... "
                f"(last reply by: {conversation['last_reply_author']})"
            )
            
            # Retrieve full thread and generate contextual reply
            try:
                thread = bot.retrieve_thread(conversation['conversation_id'])
                if thread:
                    formatted_thread = bot.format_thread_for_model(thread)
                    # Build a conversation dict for generate_reply_to_replies
                    conversation_dict = {msg['author']: msg['content'] for msg in thread}
                    
                    reply = bot.generate_reply_to_replies(
                        conversation_dict, 
                        conversation['original_tweet']
                    )
                    
                    if reply:
                        logging.info(f"Generated reply: {reply}")
                        # TODO: Optionally post the reply here
                        # bot.twitter_client.reply(reply, reply_to_tweet_id=thread[-1]['tweet_id'])
                    else:
                        logging.warning(f"Failed to generate reply for conversation {conversation['conversation_id']}")
            except Exception as e:
                logging.error(f"Error processing conversation {conversation['conversation_id']}: {e}")

        

def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    configure_logging(args.log_level)
    config = build_config(args)
    return run_bot(args, config)


__all__ = [
    "CHAT_MODEL_CHOICES",
    "build_parser",
    "parse_args",
    "build_config",
    "run_bot",
    "main",
]

if __name__ == "__main__":
    sys.exit(main())
